name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main  # Trigger deploy when pushing to the 'main' branch (you can change this to your preferred branch)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Build Docker image
      run: docker build -t similar-players-image .
    - name: Tag Docker image
      run: docker tag similar-players-image:latest ${{ secrets.ECR }}:latest
    - name: Push Docker image to ECR
      run: docker push ${{ secrets.ECR }}:latest
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_NAME }} \
          --image-uri ${{ secrets.ECR }}